### ISSUE TITLE
Parental controls on ash thermostats

### ISSUE THREAD

**Issue by kreack** [stefan-kaestle/openhab2-addons#41]
it would be great to activate / deactivate the bsh thermostats parental controls via openhab (see Kindersicherung unter BSH APP --> Verwaltung --> Geräte --> Heizkörper-Thermostate --> Zimmer --> Kindersicherung)

![IMG_ECFE64247A56-1](https://user-images.githubusercontent.com/62901914/90811371-c87a2f80-e324-11ea-877f-a903cbcc2166.jpeg)

P.S: Great performance, the binding works perfectly

**Comment by jensflorian** [comment]
I queried my thermostat under /devices/hdm:HomeMaticIP:3014F711A000239BB858E19A/services/Thermostat/state 

 and got following information:

`{
    "@type": "childLockState",
    "childLock": "OFF"
}`

**Comment by coeing** [comment]
I managed to enable/disable the child lock via Postman. The service seems to be called "Thermostat" which is kind of strange, but probably due to their API growing over time ;) Anyway we could add a new service which will be added to the thermostat thing. This service will be linked to a "child lock" channel.
