### ISSUE TITLE
Send alarm system to BSH via openhab (use integrated alarm ton in BSH APP)

### ISSUE THREAD

**Issue by kreack** [stefan-kaestle/openhab2-addons#42]
Adding of virtual Thing / Item for activation and deactivation of the alarm system / ton in the BSH APP via OepnHab. 

![IMG_0CF41679FD35-1](https://user-images.githubusercontent.com/62901914/90812535-8eaa2880-e326-11ea-83fb-b5f07c19bc9c.jpeg)

**Comment by coeing** [comment]
@kreack We don't have a handler for it in our binding, but we can implement it in the next version. But this will only work if you will help with the testing because none of us has the hardware at home.

**Comment by kreack** [comment]
@coeing of course I'm happy to support 👍

**Comment by tuxianerDE** [comment]
@coeing count me in on the testing piece here!

**Comment by VL2019** [comment]
Same here. Happy to help with a test installation

**Comment by VL2019** [comment]
FYI: there was an update for this feature in the Bosch Smart Home App. There are now three different alarm profiles. Here is the release note (german, sorry): https://www.bosch-smarthome.com/de/de/release-notes/system/2020-09-28

**Comment by VL2019** [comment]
For all who are interested in this feature (start / stop the BOSCH IntrusionDetectionSystem in OH) and can not wait until this feature is part of the beta or final version I would like to share my work-around.

First of all you have to buy a "**Bosch adapter plug**" (https://www.bosch-smarthome.com/de/de/shop?url=produkte/smart-system-solutions/zwischenstecker) 
In addition to that you can use the HomeKit binding with AppleHome or (if Siri not necessary) this beta binding to control the adapter plug.

Here my solution:
I created a virtual Alarm System in Apple Home with this items:

`Group           gSecuritySystem            "Security System Group"                                   {homekit="SecuritySystem"}
String          security_current_state     "Security Current State"             (gSecuritySystem)    {homekit="SecuritySystem.CurrentSecuritySystemState"}
String          security_target_state      "Security Target State"              (gSecuritySystem)    {homekit="SecuritySystem.TargetSecuritySystemState"}

`
You need also these rules to update the status. I have no delay in these rules because the delay is configured in the Bosch App.

`rule "Apple Home Alarm aktivieren"
when
Item security_target_state changed to "AWAY_ARM"
then
        security_current_state.postUpdate("AWAY_ARM")
end


rule "Apple Home Alarm deaktivieren"
when
Item security_target_state changed to "DISARM"
then
        security_current_state.postUpdate("DISARMED")
end

`

The Alarm System in Apple Home has nice usability (Siri) and design but of course you can use a simple virtual switch, instead of the Apple "SecuritySystem -  CurrentSecuritySystemState and TargetSecuritySystemState". Details for HomeKit SecuritySystem in OH here: [https://www.openhab.org/addons/integrations/homekit/ ](https://www.openhab.org/addons/integrations/homekit/ )

Next steps: 
--> create an automation in Apple Home like "if Alarm will be set on active, turn on the Bosch adapter plug".

--> this event of activating / deactivating Bosch Adapter Plug can be used in the Bosch Smart Home app to create a rule like "If plug turns on, activate the IntrusionDetectionSystem" and of course also the other way round to deactivate. 

But remember. if you have an HomePod or something else every one can deactivate the alarm with his / her voice. 

Not sure how reliable this works. Activate the adapter plug with the current beta solution of this binding could be more reliable. But I also like the Apple Home Alarm System. So I use this binding and Apple Home.

**Comment by david-pace** [comment]
This was implemented in https://github.com/openhab/openhab-addons/issues/12700. Please report any future issues in https://github.com/openhab/openhab-addons/issues.

**Comment by david-pace** [comment]
@stefan-kaestle or @GerdZanker, could you please close this issue? Thanks 🙂

**Comment by kreack** [comment]
Hello everyone!
do you have an example how this thing and the affected items should be configured?
thanks & regards

**Comment by stefan-kaestle** [comment]
Thanks @david-pace . I also added you to the list of collaborators, so you should be able to manage this project yourself as well.

**Comment by david-pace** [comment]
Thank you @stefan-kaestle ❤️ 

@kreack please refer to [this table](https://www.openhab.org/addons/bindings/boschshc/#intrusion-detection-system) for an overview of channels and data types for the intrusion detection system.
