### ISSUE TITLE
add "doHttpRequest" function to wrap the Bosch SHC Request code at one single place

### ISSUE THREAD

**Issue by GerdZanker** [stefan-kaestle/openhab2-addons#48]
Add a new request function into ``BoschHttpClient`` to make simple calls like ``doHttpRequest("smarthome/devices")``  possible.
We have at least three places in ``BoschSHCBridgeHandler'' where we create http requests with duplicated code parts which can be replaced by the `´doHttpRequest`` function.

Here an example

    public ContentResponse doHttpRequest(String restData) throws InterruptedException, TimeoutException, ExecutionException {
    return GET("https://" + m_ipAddress + ":8444/" + restData)
    .header("Content-Type", "application/json").header("Accept", "application/json")
    .send();
    }

**Comment by coeing** [comment]
The BoschSHCBridgeHandler has already some helper methods which could be used instead of creating a request from zero:
- `createServiceUrl`: To create the URL to send the request to
- `createRequest`: To create the request by providing the http client (might be removed), the http method, the url and the data to send

We should use those first in the places where the requests are created and add an additional method afterwards if we still see a need :)

**Comment by coeing** [comment]
@GerdZanker Did you find the methods I mentioned? Do you still see a need for additional methods?

**Comment by coeing** [comment]
@GerdZanker Should we close this issue or do you see the need for more helper methods than the ones mentioned above?

**Comment by GerdZanker** [comment]
We close this issue. In the meantime our code is refactored multiple times and better compared to last summer.
