### ISSUE TITLE
Please support Bosch's radiator thermostat

### ISSUE THREAD

**Issue by d0whiletrue** [stefan-kaestle/openhab2-addons#49]
Please consider to support Bosch's radiator thermostats in the Bosch Smart Home Binding.

https://www.bosch-smarthome.com/de/de/produkte/smart-system-solutions/heizkoerperthermostat

**Comment by armin-gh** [comment]
Hi. Works for me already
you have two things, a "thermostat" and a "climate-control". 
Thermostat reports temperature and current valve position, climate-control allows to set temperature
`  Thing thermostat      heizung1         "Heizung WZ 1" [id="hdm:HomeMaticIP:xxxxxxxxxxxxxxxxxxx" ]`
`  Thing climate-control ccwohnzimmer     "CC Wohnzimmer" [id="roomClimateControl_hz_6" ]`
 
Items for the thermostat
```
Number SHC_TempWZ1			"[%.1f] °C" <temperature>  (Wohnzimmer,gSHC) { channel="boschshc:thermostat:xxxxxxxx:heizung1:temperature" }
Number SHC_ValvWZ1          "Valv Pos WZ1" (Wohnzimmer,gSHC) { channel="boschshc:thermostat:xxxxxxxx:heizung1:valve-tappet-position" }
```

Items for climate-control
```
Number SHC_CCWZ1Set         "[%.1f] °C" <temperature> (Wohnzimmer) { channel="boschshc:climate-control:xxxxxxxx:ccwohnzimmer:setpoint-temperature"}
Number SHC_CCWZ1Now         "[%.1f] °C" <temperature> (Wohnzimmer) { channel="boschshc:climate-control:xxxxxxx:ccwohnzimmer:temperature"}
```
The IDs for the things are listed in the logs on startup, the channel for the items you'll find in PaperUI after creating the things, that's at least how I did it. Use the "copy"-Button in PaperUI, took me hours to find my typos :-)
Some of the actual IDs are masked above

Armin

**Comment by coeing** [comment]
@armin-gh described it perfect :) The radiator thermostats are already implemented and I have one at home with which I tested it. It is a bit strange that you need two things for a thermostat (the thermostats only report their temperature, but there desired temperatures are controlled via the climate controls). But on the other hand it makes sense, because you set the desired temperature per room and not per thermostat.

@d0whiletrue Please let us know if you solved your issue with the description from Armin, so we can close the issue :)

**Comment by coeing** [comment]
Closing this as the desired feature is already implemented.
